### ISSUE TITLE
Etap 3 - checklist

### ISSUE THREAD

**Issue by levitatingmoon** [levitatingmoon/TPUM#7]
Project Stage 3 Checklist
- [x] program jest w .NET
- [x] program się kompiluje
- [x] testy jednostkowe na zielono
- [x] można utworzyć jednocześnie dwie instancje programu (dwa procesy)
- [x] instancje serwera i klienta współdziałają (test integracyjny)
- [x] Oba programy maja wymagane warstwy Prezentacja, Logika, Dane
- [x] Programy komunikują się z wykorzystaniem WebSocket
- [x] Wykorzystano współdziałanie interaktywne
- [x] Wykorzystano współdziałanie reaktywne (samorzutne/subskrypcja) z wykorzystaniem mechanizmu subskrypcji zrealizowanej poprzez implementację IObservable
- [x] Wykorzystano serializacji z wykorzystaniem jednej ze składni `JSON`, `YAML`, `XML`
- [x] wydzielono sekcję krytyczną i zabezpieczono w niej spójność danych
- [x] Oba programy korzystają ze wspólnego modelu obiektowego
- [x] Harmonizacja modeli - wygenerowano ekwiwalentny model i porównano go z napisanym ręcznie
